### ISSUE TITLE
Add Google Finances as Exchange Rate implementation

### ISSUE THREAD

**Issue by otaviojava** [JavaMoney/javamoney-lib#23]
Add Google Finances as Exchange Rate implementation
http://www.google.com/finance/converter?a=1&from=BRL&to=USD
https://www.google.com/finance/converter?a=16.6700&from=GBP&to=USD

**Comment by keilw** [comment]
Does Google Finance still exist? If so, sure, these are the extensions that make sense right away on top of Moneta 1.0.x ;-)

**Comment by otaviojava** [comment]
:(, the Google Finances is deprecated, so not make sense to create an implementation.
