### ISSUE TITLE
Remove IMF and ECB providers from lib

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-lib#26]
The EMFand ECB (out-of-the-box) provider should be moved as modules (back) into RI.
Moneta/BP can perfectly use a module under an Umbrella POM but external dependencies used by Moneta/BP would create a circular dependency between RI and an external module using it.

**Comment by otaviojava** [comment]
@keilw I am just waiting the discussion about the modularization on RI. If will go or not go. To discuss the best strategy to put the exchange rate providers, if they stay on RI project or we can create a project to put all exchange rate provider and add, just these two, as dependency.

**Comment by keilw** [comment]
Your picture got it right, and even in a "Jigsaw" world where IMF and ECB provider might be optional or user-defined, having them as modules underneath RI makes perfect sense. Others "out in the wild" are subject to extensions. It just does not work to have RI "pull in" something by default, it must be part of RI. @atsticks was pretty clear about that in the discussion thread. If there's no input (@jodastephen was just defending his questionable and outdated JDK 1 era design decisions in java.time, before he decided to leave the mailing list;-) other than what we got it is up to the Maintenance Lead to decide what's best for the RI.

**Comment by keilw** [comment]
Just see @atsticks's mail a little while ago. I think he answered the questions for the "default" providers.

**Comment by keilw** [comment]
@otaviojava Unfortunately you created some toxic mix-up between "convert" and "function". Not only tests but some convenience Lambda stuff now makes modularizing harde;-(

**Comment by otaviojava** [comment]
No.
I am using just interface on the test.
Just create an implementation to test.
I take care this.

**Comment by keilw** [comment]
It was in "function", is it now in the new "convert" module?

**Comment by otaviojava** [comment]
These functions sum, average using the rate to convert, etc. using the Exchange Rate Provider, but they remain one function. I believe it's the best place for them.
