### ISSUE TITLE
Update license headers

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-lib#38]
To make this a community effort and reflect the true nature of contributors, we should apply a similar pattern as Red Hat, MicroProfile etc.

Unlike the actual JSR where the Spec Lead is Credit Suisse until it may change some day, here the legal entities can simply be @atsticks, @otaviojava, myself or others.

So we should address this in the license headers, too (the READMe file already does)

**Comment by atsticks** [comment]
Can you provide a header example?

**Comment by keilw** [comment]
It's here https://github.com/JavaMoney/javamoney-lib/blob/master/src/etc/header.txt
Not sure if we wanted to add others? the only notable contribution here came from @manuela-grindei
