### ISSUE TITLE
Prepare Calculation for Java 8/9

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-lib#5]
The Calculation interface is a skinned-down clone of Java 8 functional interface java.util.function.Function.

Should be prepared for Java 8 or 9 by using an identical method signature (only apply() method so far) allowing seamless integration of Java 8 Lambdas (Calculation extends Function) and eventual elimination of this interface in JavaMoney without affecting third party codebase.

i.E. sub-interfaces like MonetaryCalculation would then directly extend Function.

**Comment by atsticks** [comment]
The interface has been removed.
